version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: approvals
        min:
          count: 1
      # Validacion de Titulo PR
      - do: title
        must_include:
          regex: "^(FEAT|FIX|DOCS): .+"
          message: "Error: El título debe iniciar con 'FEAT: ', 'FIX: ', 'DOCS: '"