version: "1.1"
rules:
  - name: "Validar Formato del Título"
    pull_request:
      types: [opened, edited, synchronize]
    validate:
      - do: title
        must_match:
          regex: "^(FEAT|FIX|DOCS|REFACTOR): .+"
          message: "Error: El título debe iniciar con 'FEAT: ', 'FIX: ',"