version: "2"
mergeable:
  - name: "Validacion de Nombres"
    index: 1
    validate:
      - do: title
        must_match:
          regex: "^(FEAT|FIX|DOCS|REFACTOR): .+"
          message: "Error: El título debe iniciar con 'FEAT: ', 'FIX: ', 'DOCS: ', 'REFACTOR: '"