rootLogger.level = ${sys:logLevel:-INFO}
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = STDOUT

#rootLogger.level = debug

name = Log4j2Config

appender.console.type = Console
appender.console.name = STDOUT

appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %style{%d{yyyy-MM-dd HH:mm:ss}}{cyan} %style{[%t]}{magenta} %highlight{%-5p (%F:%M:%L)}{INFO=green, WARN=yellow, ERROR=red} - %m%n