# Usa una variable de sistema; si no existe, por defecto es INFO

#Configuracion de Logger
#rootLogger.level = ${sys:logLevel:-INFO}
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = STDOUT

#Forzar para modo debug
rootLogger.level = debug

# Establece el nombre de la configuración
name = Log4j2Config

# Define el Appender de Consola
appender.console.type = Console
appender.console.name = STDOUT

# Configuración del Layout con colores
# %style{%d...}{cyan}: Fecha en cian
# %highlight{%p}{...}: Nivel con colores (INFO=verde, WARN=amarillo, ERROR=rojo)
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %style{%d{yyyy-MM-dd HH:mm:ss}}{cyan} %style{[%t]}{magenta} %highlight{%-5p (%F:%M:%L)}{INFO=green, WARN=yellow, ERROR=red} - %m%n